
name: SWE API CI

on:
  push:
    branches: 
      - develop
      - master
      - feature/**
  pull_request:
    branches: 
      - develop
      - master
      - feature/**

jobs:

  build_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
      with:
        path: apirest/ 
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build package
      run: mvn -B package
    - name: Run SonarCloud
      run: mvn verify sonar:sonar -Dsonar.login=${{secrets.SONARCLOUD_LOGIN_KEY}}
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'Build Check'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'Docs Pull Request Patrol'
        url: ${{ secrets.SLACK_WEBHOOK }}


