name: SWE Gateway CI

on:
  push:
    branches: 
      - develop
      - master
      - feature/**
  pull_request:
    branches: 
      - develop
      - master
      - feature/**

jobs:
  ci_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run project checkstyle
      run: mvn clean validate --file gateway/pom.xml
    - name: Run project build 
      run: mvn clean compile --file gateway/pom.xml
    - name: Run project tests
      run: mvn clean test --file gateway/pom.xml
    - name: Run project SonarCloud
      run: mvn clean verify -Dsonar.login=${{ secrets.SONARCLOUD_LOGIN_KEY }} --file gateway/pom.xml -e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'CI Check'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'CI Checker'
        url: ${{ secrets.SLACK_SW_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
