name: SWE Telegram CI

on:
  push:
    branches: 
      - develop
      - master
      - feature/**
  pull_request:
    branches: 
      - develop
      - master
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run dependencies installation
      run: npm ci
    - name: Run project formatter and linter
      run: npm run prettier-eslint
    - name: Run project build
      run: npm run build --if-present
    - name: Run project test 
      run: npm test
      env:
        CI: true
    - name: Run Coveralls report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'CI Check'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'CI Checker'
        url: ${{ secrets.SLACK_SW_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}  
