version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  api:
    container_name: thirema_api
    build: ./swe-api
    networks:
      - kafka-net
    ports:
      - "9999:9999"
  telegram_bot:
    container_name: thirema_telegram_bot
    build: ./swe-telegram
    networks:
      - kafka-net
    ports:
      - "3000:3000"
  
    