version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  api:
    container_name: thirema-api
    build: ./swe-api
    networks:
      - kafka-net
    ports:
      - "9999:9999"
  telegram_bot:
    container_name: thirema-telegram-bot
    build: ./swe-telegram
    networks:
      - kafka-net
    ports:
      - "3000:3000"

  # Under testing
  gateway:
    container_name: thirema-gateway
    build: ./swe-gateway
    networks:
      - kafka-net
      
  data_collector:
    container_name: thirema-data-collector
    build: ./swe-kafka-db
    networks:
      - kafka-net

  webapp:
    container_name: thirema-webapp
    build: ./swe-webapp
    networks:
      - kafka-net
    ports:
      - "8000:8000"
  
    