name: SWE Web App CI

on:
  push:
    branches:
      - develop
      - master
      - feature/**
  pull_request:
    branches:
      - develop
      - master
      - feature/**

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run dependencies installation
      run: npm ci
    # - name: Run project formatter and linter
    #   run: npm run prettier-eslint
    - name: Check project formatter and linter
      run: npm run prettier-eslint-check
    # - name: Run project formatter and linter for tests
    #   run: npm run prettier-eslint-test
    - name: Check project formatter and linter for tests
      run: npm run prettier-eslint-test-check
    - name: Run project build
      run: npm run build --if-present
    - name: Run project test
      run: npm test
      env:
        CI: true
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: touch database/database.sqlite
    # - name: Run code style fixer
    #   run: vendor/bin/phpcbf -n
    - name: Run code style sniffer
      run: vendor/bin/phpcs -s
    # - name: Run code style fixer
    #   run: vendor/bin/php-cs-fixer fix --config=.php_cs.php --diff -vvv
    - name: Run code style checker
      run: vendor/bin/php-cs-fixer fix --config=.php_cs.php --dry-run -vvv
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit -c phpunit.xml
    - name: Report to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_LARAVEL }}
      run: vendor/bin/php-coveralls -v
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'CI Check'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'CI Checker'
        url: ${{ secrets.SLACK_SW_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
